apiVersion: v1
kind: PersistentVolume

metadata:
  name: {{ include "tiddlywiki.fullname" . }}-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: specify_host_path

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tiddlywiki.fullname" . }}-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ include "tiddlywiki.fullname" . }}-volume