apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiddlywiki.fullname" . }}-np
  labels:
    {{- include "tiddlywiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nodeService.type }}
  ports:
  - port: {{ .Values.nodeService.externalPort }}
    targetPort: {{ .Values.nodeService.internalPort }}
    protocol: TCP
    name: {{ .Values.nodeService.name }}
    nodePort: {{ .Values.nodeService.nodePort }}
  selector:
    {{- include "tiddlywiki.selectorLabels" . | nindent 4 }} 